package test.java.com.goeuro;

import org.openqa.selenium.TimeoutException;
import test.java.com.goeuro.Helpers.PrintOptions;
import test.java.com.goeuro.configuration.GeneralTestPreparation;
import test.java.com.goeuro.goEuroPageObjects.*;
import org.openqa.selenium.support.PageFactory;
import org.testng.Assert;
import org.testng.annotations.Test;

/**
  * Class with stores test for technical assignment:
 GoEuro lists the travel results sorted by cheapest, fastest or by time (departure/arrival). Please
 create an automated test that will make a search (Eg.: Berlin Prague)
 and will verify that the
 sorting by price is correct. You are free to choose the tool and language you want, except for
 record and play tools.

 Test was realized with following requirements and assumptions
   - search is done for one-way - by default
   - search is done for  - default "cheapest" tab found results option and on opened "train" tab option
   - search is done without selecting airbnb or booking.com options
   - search is done for tomorrow date - as default
   - search is done with "no BahnCard" option - as default
   - search is performed for 1 person - as default

 No custom reports were implemented - usual TestNG html variant is generated by surefire plugin.

 */
public class SearchVerificationTest extends GeneralTestPreparation {
        @Test
        public void searchForTravel () {
        MainSearchPage page = PageFactory.initElements(driver, MainSearchPage.class);
            try {
        FoundResultsPage pageWithResults = page.findAvailableTrips("Berlin, Germany", "Prague, Czech Republic");
            Assert.assertTrue(pageWithResults.isPricesSortedAcs());
        }
        catch (TimeoutException e)
        {
            PrintOptions.print("Test fails due to time out while waiting for page load.");
            throw e;
        }
    }
    }
